/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    double v[],v1[];
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLongitud1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtElementos1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtElementos2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenarManual = new javax.swing.JButton();
        cmdLlenarAuto = new javax.swing.JButton();
        cmbOperacion = new javax.swing.JComboBox<>();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel2.setText("Longitud vector 2:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        txtLongitud2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud2KeyTyped(evt);
            }
        });
        jPanel3.add(txtLongitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 60, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel3.setText("Longitud vector 1:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtLongitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitud1ActionPerformed(evt);
            }
        });
        txtLongitud1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud1KeyTyped(evt);
            }
        });
        jPanel3.add(txtLongitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 50, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 410, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("OPERACION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "vector 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtElementos1.setEditable(false);
        txtElementos1.setColumns(20);
        txtElementos1.setRows(5);
        jScrollPane2.setViewportView(txtElementos1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 70));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "vector 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtElementos2.setEditable(false);
        txtElementos2.setColumns(20);
        txtElementos2.setRows(5);
        jScrollPane1.setViewportView(txtElementos2);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 70));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 180, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane3.setViewportView(txtResultado);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 90));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        cmdLlenarManual.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdLlenarManual.setText("Llenar Manual");
        cmdLlenarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLlenarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        cmdLlenarAuto.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdLlenarAuto.setText("Llenar Auto");
        cmdLlenarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarAutoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLlenarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        cmbOperacion.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operación...", "Union", "Interseccion", "Diferencia A-B", "Diferencia B-A" }));
        jPanel2.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, -1));

        cmdMostrar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        cmdBorrar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 170, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLongitud2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtLongitud2KeyTyped

    private void txtLongitud1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud1KeyTyped

    private void txtLongitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud1ActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int longitud1,longitud2;
        if (txtLongitud1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Longitud vector 1","error",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
        }else if (Integer.parseInt(txtLongitud1.getText().trim())==0){
            JOptionPane.showMessageDialog(this, "La longitud no puede ser Cero","error",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
            txtLongitud1.selectAll();
        }else{
            longitud1=Integer.parseInt(txtLongitud1.getText());
            v = new double [longitud1];
            JOptionPane.showMessageDialog(this,"Vector 1 creado exitosamente");
        }
        if (txtLongitud2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Longitud vector 2","error",JOptionPane.ERROR_MESSAGE);
            txtLongitud2.requestFocusInWindow();
        }else if (Integer.parseInt(txtLongitud2.getText().trim())==0){
            JOptionPane.showMessageDialog(this, "La longitud no puede ser Cero","error",JOptionPane.ERROR_MESSAGE);
            txtLongitud2.requestFocusInWindow();
            txtLongitud2.selectAll();
        }else{
            longitud2=Integer.parseInt(txtLongitud2.getText());
            v1 = new double [longitud2];
            JOptionPane.showMessageDialog(this,"Vector 2 creado exitosamente");
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarManualActionPerformed
        // TODO add your handling code here:
        double n;
        txtElementos2.setText("");
        txtResultado.setText("");
        cmbOperacion.setSelectedIndex(0);
        for (int i = 0; i < v.length; i++) {
            n=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el elemento en la posición " + i + " del vector 1"));
            v[i]=n;
        }
        for (int j = 0; j < v.length; j++) {
            txtElementos1.append(v[j]+"\n");
        }
        for (int k = 0; k < v1.length; k++) {
            n=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el elemento en la posición " + k + " del vector 2"));
            v1[k]=n;
        }
        for (int l = 0; l < v1.length; l++) {
            txtElementos2.append(v1[l]+"\n");
        }
    }//GEN-LAST:event_cmdLlenarManualActionPerformed

    private void cmdLlenarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarAutoActionPerformed
        // TODO add your handling code here:
        double n;
        for (int i = 0; i < v.length; i++) {
            n=(int)(Math.random()* 100 + 1);
            v[i]=n;
        }
        for (int k = 0; k < v1.length; k++) {
            n=(int)(Math.random()* 100 + 1);
            v1[k]=n;
        }
        txtElementos2.setText("");
        txtElementos1.setText("");
        txtResultado.setText("");
        cmbOperacion.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this,"Vectores llenados automaticamente");
        for (int j = 0; j < v.length; j++) {
            txtElementos1.append(v[j]+"\n");
        }
        for (int l = 0; l < v1.length; l++) {
            txtElementos2.append(v1[l]+"\n");
        }
    }//GEN-LAST:event_cmdLlenarAutoActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        double suma=0,resta=0;
        int op;
        op= cmbOperacion.getSelectedIndex();
        double vr[];
        switch(op){
            case 0:
            JOptionPane.showMessageDialog(this,"Seleccione operacion","Error",JOptionPane.ERROR_MESSAGE);
            cmbOperacion.requestFocusInWindow();
            break;
            case 1:

            break;
            case 2:

            break;
            case 3:

            break;
            case 4:

            break;

        }
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtElementos2.setText("");
        txtElementos1.setText("");
        txtLongitud2.setText("");
        txtResultado.setText("");
        cmbOperacion.setSelectedIndex(0);
        txtLongitud1.setText("");
        txtLongitud1.setText("");
        txtLongitud1.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenarAuto;
    private javax.swing.JButton cmdLlenarManual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtElementos1;
    private javax.swing.JTextArea txtElementos2;
    private javax.swing.JTextField txtLongitud1;
    private javax.swing.JTextField txtLongitud2;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
